### PR TITLE
rustfmt: use nightly in CI

### PR DESCRIPTION
**Pull request by buffalojoec**
This PR opts for using the `nightly` channel in CI for `rustfmt`.

### CODE REVIEW

**Comment by buffalojoec** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5741** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5741" target="_blank">Graphite</a> 
    * **PR #5742** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5742" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5742?utm_source=stack-comment).

**Review by joncinque — COMMENTED** [review]
Along with this change, can you add a `cargo-nightly` script similar to the `cargo` script in the monorepo? It literally just needs to do:

```
#!/usr/bin/env bash

here=$(dirname "$0")
source "${here}"/ci/rust-version.sh nightly
# shellcheck disable=SC2054 # rust_nightly is sourced from rust-version.sh
toolchain="$rust_nightly"
set -x
exec cargo "+${toolchain}" "${@}"
```

This will make it easier to run `fmt` or `clippy` since you can just call `./cargo-nightly fmt` or whatever. I've long used shell history to know the right nightly version to use, but a helper script will be good for other devs too. What do you think?

**Review by joncinque — APPROVED** [review]
Looks great!

**Comment by buffalojoec** [comment]
### Merge activity

* **Nov 8, 3:35 PM**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5742).

**Pull request merged**
