### PR TITLE
Use ristretto_mul builtin to stay below BPF instruction limit

### PR DESCRIPTION
**Pull request by garious**
#### Problem

CalculateAggregate and SubmitProofDecryption operations exceed the BPF instruction limit

#### Proposed changes

Use the new `ristretto_mul` and Sha256 builtins to stay below the BPF instruction limit.

All operations will now stay below the limit in the forthcoming 1.4 testnet:

```
BPF instructions executed
  InitializePolicies(2): 3,354 (80000)
  InitializeUserAccount: 19,746 (22000)
  CalculateAggregate:    87,220 (200000)
  SubmitProofDecryption: 105,372 (200000)
```

### CODE REVIEW

**Comment by garious** [comment]
@jackcmay, `./do.sh build themis/program_ristretto` works, but `./do.sh test themis/program_ristretto` does not. Here's the error:

```
= note: Undefined symbols for architecture x86_64:
            "_sol_sha256", referenced from:
                solana_sdk::hash::hashv::hd997747d4e8788d2 in libsolana_sdk-d76af880bd1a8666.rlib(solana_sdk-d76af880bd1a8666.solana_sdk.pr9byz1w-cgu.2.rcgu.o)
            "_sol_ristretto_mul", referenced from:
                elgamal_ristretto::multiply::ristretto_mul::h2933a249c853aae8 in spl_themis_ristretto-681b76e19ec915a1.1cc4a21hpvff15hg.rcgu.o
                elgamal_ristretto::multiply::ristretto_mul::h1d256baae8d8da1b in libelgamal_ristretto-19dbc4ea687fc40a.rlib(elgamal_ristretto-19dbc4ea687fc40a.elgamal_ristretto.2cwee8lb-cgu.12.rcgu.o)
```

How should I be adding those implementations?

**Comment by jackcmay** [comment]
Ah, I'm missing a feature check in the sdk, hold please...

**Comment by jackcmay** [comment]
@greg Try this: https://github.com/solana-labs/solana/pull/12714

**Comment by garious** [comment]
Thanks @jackcmay, it's looking like that fix did the trick. A couple nits:
* I think the solana ristretto crate needs to be a `lib`
* A comment in that library: mulitply -> multiply
* I have to copy-paste it anyway since I forked curve25519-dalek

**Comment by jackcmay** [comment]
Great, yeah I was expecting you to copy, don't think we should point people to an example program to get the ristretto helper.  If we decide to keep this stuff I'll spend the time to clean it up

**Comment by garious** [comment]
Merging this since it passes CI. There will be a follow-up PR once solana-sdk 1.4.0 is released.

**Pull request merged**
