### PR TITLE
Added "Edit this page" link to docs

### PR DESCRIPTION
**Pull request by daertommy**
With this PR readers can suggest changes to the docs with an easy to use WYSIWYG markdown editor.

[This](https://holocron.so/github/pr/solana-labs/solana-program-library/master/editor) is how the editor looks like for this repo.

https://github.com/remorses/docusaurus-example/assets/31321188/43c8bc68-3668-4a25-bf1c-a70eceab7bcb

### CODE REVIEW

**Comment by buffalojoec** [comment]
This is really cool! Would we need to add any applications to the repository with permissions of some sort?

**Comment by buffalojoec** [comment]
I love it, but it seems to be taking a looong time to load for me.

**Comment by daertommy** [comment]
Does it take a long time after clicking the "open pr" button? or just loading the website?

**Comment by buffalojoec** [comment]
I got it to load after a refresh.

This is a really cool feature, and I appreciate you PR'ing this into the library. However, I don't want to add this feature yet. We will likely give the docs a makeover and we don't want to confuse contributors with the multiple auth steps and routing to a web editor.

I'll be sure to surface this PR whenever we revisit the docs stuff!

**Comment by daertommy** [comment]
Ok, thank your for giving me some feedback!

**Pull request closed without merging**
