### PR TITLE
Add c examples

### PR DESCRIPTION
**Pull request by jackcmay**
Add C examples

Testing is limited to none due to lack of any meaningful full framework

### CODE REVIEW

**Comment by OluAgunloye** [comment]
One of these no longer works:
https://github.com/solana-labs/solana-program-library/blob/96b3b5691f05b6744f32ba0926f5e2b2bbf3534b/examples/c/src/logging/logging.c#L24

**Comment by jackcmay** [comment]
Hey @OluAgunloye , thanks for taking an interest!

The declaration for `sol_log_params` is here: https://github.com/solana-labs/solana/blob/2a795614d3a60e87614c6647f39dd77ba6106c95/sdk/bpf/c/inc/sol/log.h#L48

and only takes one parameter which is `SolParameters`.  Can you elaborate on what the issue is you are seeing?

**Comment by OluAgunloye** [comment]
> Hey @OluAgunloye , thanks for taking an interest!
> 
> The declaration for `sol_log_params` is here: https://github.com/solana-labs/solana/blob/2a795614d3a60e87614c6647f39dd77ba6106c95/sdk/bpf/c/inc/sol/log.h#L48
> 
> and only takes one parameter which is `SolParameters`. Can you elaborate on what the issue is you are seeing?

Hello @jackcmay,

This line outputs an error if you use web3.js on the devnet in the BPF code. I've checked the program in the block explorer multiple times and it always errors on that specific line.

**Comment by OluAgunloye** [comment]
While I have your attention, by the way, how do I implement my own custom headers in C files? All of the functions I've attempted to use in my .cc files are not found even if the header is linked correctly.

**Comment by jackcmay** [comment]
Can you send me links to the transactions you see the errors on?

**Comment by jackcmay** [comment]
> While I have your attention, by the way, how do I implement my own custom headers in C files? All of the functions I've attempted to use in my .cc files are not found even if the header is linked correctly.

What functions are you trying to call?

**Comment by OluAgunloye** [comment]
> > While I have your attention, by the way, how do I implement my own custom headers in C files? All of the functions I've attempted to use in my .cc files are not found even if the header is linked correctly.
> 
> What functions are you trying to call?

C++ standard library functions which I tried to add from https://github.com/solana-labs/llvm-project as well as my own custom headers and function definitions.

**Comment by jackcmay** [comment]
We call `sol_log_params` as part of our testing, can you provide links to a failed tx or instructions on how I can recreate this issue?

**Comment by OluAgunloye** [comment]
First, create a file called: `logging.js` then just input the following into the file:

`var solana_web3 = require('@solana/web3.js');
// programId = new solana_web3.PublicKey('');
programId = new solana_web3.PublicKey('');
function testMemo(connection, account) {
  const instruction = new solana_web3.TransactionInstruction({
    programId,
    keys: [{ isSigner: true, isWritable: true, pubkey: account.publicKey }],
    data: Buffer.from('testing'),
  });
  // console.log("account:", account.publicKey.toBase58(), "\n private key:", account.secretKey.toString('base64'))
  solana_web3.sendAndConfirmTransaction(
    connection,
    new solana_web3.Transaction().add(instruction),
    [account],
    {
      skipPreflight: true,
      commitment: "confirmed",
    },
  ).then(() => { console.log("done") }).catch((e) => { console.log("error", e) });
} function main() {
  connection = new solana_web3.Connection(solana_web3.clusterApiUrl("devnet"), 'confirmed');
  //let hello = new Buffer.from("", 'base64');
  //client account pubkey: 
  const account = new solana_web3.Account();
  const lamports = 10 * 1000000000
  connection.requestAirdrop(account.publicKey, lamports).then(() => {
    console.log("airdrop done");
    testMemo(connection, account);
  });
  // testMemo(connection, account);
}
main()`

**Comment by OluAgunloye** [comment]
> Sounds like you would need to link in those stdlib libraries. I think this is a question better answered on discord #developer-support

Tried, but they either didn't know the answer, refused to provide a valid answer (one literally told me Rust is better supported, just move to Rust or submit a PR for C/C++ with my custom code), or just refused to answer.  As this is not a satisfactory state of affairs, I thought I'd go directly to someone maintaining the code with the hands-on experience necessary to answer the question(s).  what code in the `sys` packages _can_ be used safely in Solana?

**Comment by jackcmay** [comment]
Try again, I'll try and pick it up

**Comment by jackcmay** [comment]
Hmm, that js confuses me, looks like you are sending a transaction to the system program?

Can you she me an example failure?

**Comment by OluAgunloye** [comment]
> Hmm, that js confuses me, looks like you are sending a transaction to the system program?
> 
> Can you she me an example failure?

https://explorer.solana.com/tx/3LbJJRWobDqvpchCJ3WtqWXrHxiEgZydPCjaJzzqMngMtYBmFmc8599drDcmD1veuc9L8fsRVKC4QpFctkH5XfoK?cluster=devnet

From Program ID = 4JYUvbazdFH8dtCixq1NsSaPE2o3B4zAVsbVEnQcjQYw

**Pull request merged**
