### PR TITLE
Fix CI post-Themis

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

The Themis PR took a hammer to CI

#### Changes

Re-enable token CLI
Run Themis client tests in CI

### CODE REVIEW

**Review by garious — DISMISSED** [review]
Cool, but we still need to keep themis/client in the excludes?

**Comment by t-nelson** [comment]
Yeah. `xargo` blows away the target dir for whatever reason, so `themis/client`'s `build.rs` rug pulls the symbols out from under the workspace build.

It can still be built directly.

**Comment by garious** [comment]
Got it, thanks for the analysis!

**Comment by t-nelson** [comment]
https://travis-ci.com/github/solana-labs/solana-program-library/jobs/393425450#L4802

@garious any insights into this test failure? It passed locally three times last night.  The only one I saw fail was one of the e2e (that hits devnet?)

**Comment by garious** [comment]
@t-nelson, sorry about that. Can you bump BASELINE_PROOF_DECRYPTION_COUNT to 60,000,000?

**Pull request merged**
