### PR TITLE
program error: bump patch version

### PR DESCRIPTION
**Pull request by buffalojoec**
Bumps the patch version of program error after #6590.

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
Unless they need the new version, can we keep the downstream deps on 0.4.0? I got screwed pretty badly by the patch releases last time and wasted a whole day getting the deps to work out for token-cli because of patch bumps.

**Comment by buffalojoec** [comment]
> Unless they need the new version, can we keep the downstream deps on 0.4.0? I got screwed pretty badly by the patch releases last time and wasted a whole day getting the deps to work out for token-cli because of patch bumps.

Oh yeah sure, but I think they'd have to get modified to say `"4.0"` since they use `path`, right?

**Comment by joncinque** [comment]
As long as we keep it as `0.4.0` everywhere, it should pull in either. At least, it worked with my local testing

**Review by joncinque — APPROVED** [review]
Thanks!

**Pull request merged**
