### PR TITLE
CI: Isolate solana bins

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

CI installs solana bins in the user's home directory, clobbering any existing installation

#### Changes

Isolate the install to the local directory

### CODE REVIEW

**Review by mvines — DISMISSED** [review]

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana-program-library/blob/81e86172e183ca4a350962258088c361f0cdee17/examples/c/makefile#L2

Oh hi

**Comment by t-nelson** [comment]
@mvines mind taking another peek?  I "fixed" the makefile path and also added a check so we don't redownload bins if we already have the right version

**Comment by t-nelson** [comment]
But wait... there's more!

**Comment by t-nelson** [comment]
Demoting to draft until I have some time to sort out the cached .d issue

**Pull request closed without merging**
