### PR TITLE
Features/token wrap impl

### PR DESCRIPTION
**Pull request by staccDOTsol**
@joncinque responded to most of your comments. sorry for the delay

### CODE REVIEW

**Comment by buffalojoec** [comment]
Hey @staccDOTsol is it easier if we just re-open the original PR where Jon's comments are?

Alternatively, a brand-new PR (maybe this one here) with some re-written commit history would be much easier to review - given the time elapsed - but that's up to you!

**Comment by cbates8979** [comment]
Either way I'm not picky what ever u think is easier for me. I sure appreciate you thank you

**Comment by buffalojoec** [comment]
> Either way I'm not picky what ever u think is easier for me. I sure appreciate you thank you

Lol. Are you the same guy? 🤔

**Comment by cbates8979** [comment]
Just to tired this am lmao I’m usually cussing huh well I guess u know me 😜well already. I love u 😘 yr alright Christina BatesOn Mar 22, 2024, at 9:03 AM, Joe C ***@***.***> wrote:﻿

Either way I'm not picky what ever u think is easier for me. I sure appreciate you thank you

Lol. Are you the same guy? 🤔

**Comment by cbates8979** [comment]
Joe u think my solana wallet will work after that. Either way thank u Joe 😌Christina BatesOn Mar 22, 2024, at 10:12 AM, Christina Bates ***@***.***> wrote:﻿Just to tired this am lmao I’m usually cussing huh well I guess u know me 😜well already. I love u 😘 yr alright Christina BatesOn Mar 22, 2024, at 9:03 AM, Joe C ***@***.***> wrote:﻿

Either way I'm not picky what ever u think is easier for me. I sure appreciate you thank you

Lol. Are you the same guy? 🤔

**Comment by cbates8979** [comment]
Joe a guy named Andrew at Aurora said he would help me build that part of my wallet transfer and wallet build from tron Binance is that ok? Andrew is it ok to share the transaction hash that built my near explorer he asked for near explorer trans hash ? Christina BatesOn Mar 22, 2024, at 10:13 AM, Christina Bates ***@***.***> wrote:﻿Joe u think my solana wallet will work after that. Either way thank u Joe 😌Christina BatesOn Mar 22, 2024, at 10:12 AM, Christina Bates ***@***.***> wrote:﻿Just to tired this am lmao I’m usually cussing huh well I guess u know me 😜well already. I love u 😘 yr alright Christina BatesOn Mar 22, 2024, at 9:03 AM, Joe C ***@***.***> wrote:﻿

Either way I'm not picky what ever u think is easier for me. I sure appreciate you thank you

Lol. Are you the same guy? 🤔

**Comment by staccDOTsol** [comment]
> Hey @staccDOTsol is it easier if we just re-open the original PR where Jon's comments are?
> 
> Alternatively, a brand-new PR (maybe this one here) with some re-written commit history would be much easier to review - given the time elapsed - but that's up to you!

sorry I ended up in England to do some stuff for pump.fun and haven't had any free time. I may need to pass the torch for this one off to the next foss engineer who wants to take a crack at it. I really want to see this in prod so I can mess with CLMMs by having synth tokens to create opposing dichotomous pools

wen

**Comment by staccDOTsol** [comment]
> Hey @staccDOTsol is it easier if we just re-open the original PR where Jon's comments are?
> 
> Alternatively, a brand-new PR (maybe this one here) with some re-written commit history would be much easier to review - given the time elapsed - but that's up to you!

I can't reopen the pr :) I'd appreciate if you can, then close this one. They're the same branch.

**Comment by staccDOTsol** [comment]
hi <3 is this still open for submissions or deos my current state of affairs preclude me from solana prs

**Pull request closed without merging**
