### PR TITLE
Added the typescript implementation of SPL Memo Program - MLH

### PR DESCRIPTION
**Pull request by Anurag5086**
Added the typescript implementation of SPL Memo Program.

### CODE REVIEW

**Comment by jnappy** [comment]
@Anurag5086 - are you waiting on review?

**Comment by jordansexton** [comment]
Worth noting there's a draft PR for this by @CriesofCarrots @ https://github.com/solana-labs/solana-program-library/pull/2583

**Comment by CriesofCarrots** [comment]
> Worth noting there's a draft PR for this by @CriesofCarrots @ #2583

@joncinque and I were just talking about that other one today, and plan to get it finished up and landed!

**Comment by joncinque** [comment]
Closing since this was done in #2583

**Pull request closed without merging**
