### PR TITLE
Release Token TS client bindings

### PR DESCRIPTION
**Pull request by jordansexton**
This PR makes some minor fixes, moves the existing `js` dir to `js-old`, and moves the `ts` dir to `js`.

We should integrate the necessary changes from the `js-old` directory and delete it before merging.

### CODE REVIEW

**Comment by joncinque** [comment]
All right, that was very tedious, but it's done! :crossed_fingers: on CI now

**Comment by joncinque** [comment]
Are there any other "necessary changes" to port over that you know of? If not, I can nuke `js-old`

**Review by joncinque — APPROVED** [review]
`js-old` has been blasted as well, this is good to go on my side.

**Comment by jordansexton** [comment]
> Incidentally, is there a reason this was built in a branch on the solana-labs repo, instead of from a fork?

Ah, was just my default since it's easier to manage. I can use a fork in the future if that's preferred?

**Comment by CriesofCarrots** [comment]
> I can use a fork in the future if that's preferred?

Yes, please :) Easier maintenance of the labs repos that way.

**Comment by joncinque** [comment]
Anything holding this up?

**Comment by jordansexton** [comment]
I think we are good to go! I'll release the docs on Github Pages, just waiting to hear back from someone with access.

**Pull request merged**
