### PR TITLE
token-swap: Cleanup check

### PR DESCRIPTION
**Pull request by joncinque**

### CODE REVIEW

**Comment by joncinque** [comment]
This now takes care of everything in #693

**Comment by jstarry** [comment]
@joncinque I think a good convention would be to always check the account owner when unpacking external accounts. We have this pattern for sysvars now and we could apply it to swap's `unpack_token_account` and `unpack_mint` methods too. 

It would also be nice to establish the pattern of being careful about what accounts are passed to invoked instructions but that feels less critical

**Comment by joncinque** [comment]
@jstarry that's a good point, I'll do that here.  To help other programs avoid this, what would you say to expanding `Pack` to include an `unpack` variant which takes in `AccountInfo` and an expected program id?  We can then rename the current `unpack` to `unpack_raw` or something better.

**Comment by joncinque** [comment]
@jstarry this is ready for another look whenever you get the chance

**Review by jstarry — COMMENTED** [review]
I opened a PR that applies my feedback here: https://github.com/joncinque/solana-program-library/pull/2

I thought that it was too confusing to test the curves when fees are involved so I separated that out and added more edge case tests for the rounding.

All the program id checks look good!

**Pull request merged**
