### PR TITLE
Fix usage of anchor's idl-build feature in account compression

### PR DESCRIPTION
**Pull request by ngundotra**

### CODE REVIEW

**Comment by ghulamMustafaRaza** [comment]
@ngundotra seams lik this is not published on createshttps://docs.rs/crate/spl-concurrent-merkle-tree/0.4.1/features

**Comment by ngundotra** [comment]
@ghulamMustafaRaza You are right, cutting a new release for v0.4.2. 

Note that the batch init instructions are devnet-only for now.

**Comment by ngundotra** [comment]
Tracking here: https://github.com/solana-labs/solana-program-library/pull/7371

**Comment by ngundotra** [comment]
@ghulamMustafaRaza should be fixed now https://docs.rs/crate/spl-account-compression/0.4.2/features

**Pull request merged**
