### PR TITLE
Bump solana to v1.10.15

### PR DESCRIPTION
**Pull request by dmakarov**

### CODE REVIEW

**Comment by dmakarov** [comment]
@joncinque is it ok to bump Solana version? I'd like to use updated bpf-tools that are available in v1.10.15 of Solana.

**Review by joncinque — APPROVED** [review]
Absolutely, looks good, thanks!

**Comment by joncinque** [comment]
Ah sorry, this is my fault.  I forgot that you should also at least run `cargo check` to update the lockfile.  Would you mind running a PR to update the lockfile?

**Comment by dmakarov** [comment]
Will do it now. No worries. I'm sorry, I didn't think about updating the lock files.

**Pull request merged**
