### PR TITLE
token-cli: Add compatibility for token-2022

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

The token CLI only works with `Tokenkeg...` and not `Tokenz...`.

#### Solution

Support both of them at once!  Most of the changes here involve deserializing accounts with extensions, and passing in the program id correctly.

### CODE REVIEW

**Comment by joncinque** [comment]
@CriesofCarrots feel free to use this branch to test RPC changes! All of the tests marked with TODO for token-2022 do not pass with token-2022, but should pass with token-2022 RPC work.

**Comment by joncinque** [comment]
@samkim-crypto if you want to use this branch, you just need to patch your SPL repo by running `./patch-crates.io path/to/your/solana/repo` and then you can start using the `program_client` in the Config object

**Comment by joncinque** [comment]
@CriesofCarrots this one's finally ready for a look too!

**Review by CriesofCarrots — APPROVED** [review]
Awesome, lgtm!

**Pull request merged**
