### PR TITLE
rustfmt: format imports

### PR DESCRIPTION
**Pull request by buffalojoec**
This PR adds import formatting configurations to the repository's `rustfmt.toml` file, and the associated changes from `cargo +nightly fmt --all`.

### CODE REVIEW

**Comment by buffalojoec** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5741** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5741" target="_blank">Graphite</a> 
    * **PR #5742** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5742" target="_blank">Graphite</a> 
      * **PR #5743** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5743" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5743?utm_source=stack-comment).

**Comment by buffalojoec** [comment]
heh, this one is huge 😅

**Review by joncinque — APPROVED** [review]
overwhelmed

Nah no worries, we can merge this as is, looks great! Just be careful, now your name will be all over the repo :wink:

**Comment by buffalojoec** [comment]
### Merge activity

* **Nov 8, 3:35 PM**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5743).

**Pull request merged**
