### PR TITLE
Update Stake with the additional deactivation flag

### PR DESCRIPTION
**Pull request by HaoranYi**
Update StakeState unpack with additional deactivation flag.

### CODE REVIEW

**Comment by HaoranYi** [comment]
Build and all tests passed with https://github.com/solana-labs/solana/pull/32524

**Comment by HaoranYi** [comment]
Build and tests passed with https://github.com/solana-labs/solana/pull/32524.

**Review by 2501babe — APPROVED** [review]

**Comment by 2501babe** [comment]
looks good up to here, obviously waiting on new monorepo version to finish this pr

**Comment by joncinque** [comment]
This was not ready to be merged since the upstream changes are not in the monorepo yet. Reverting this in #4841

**Pull request merged**
