### PR TITLE
Implement docusaurus build, deployment and CI hooks

### PR DESCRIPTION
**Pull request by danpaul000**
Initial implementation of docusaurus and CI infrastructure for SPL docs.  Docs content are just copies of the READMEs at the moment.

Currently served to both:
spl.docs.solana.com
spl-docs.solana.com

Does someone have an opinion on which domain to use?

CI will publish to the final domain each time the `docs` dir is touched on any commit to master.

### CODE REVIEW

**Comment by mvines** [comment]
I like spl-docs.solana.com more than spl.docs.solana.com (not a fan of the spl.docs.solana.com subdomain)

program-library.solana.com?

**Comment by garious** [comment]
How about `spl.solana.com`?

**Comment by danpaul000** [comment]
I hear three options above from the two of you @mvines and @garious  :)  What'll it be?

**Comment by danpaul000** [comment]
> I hear three options above from the two of you @mvines and @garious :) What'll it be?

This PR is not blocked by a choice or change of the domain, so we can pick one separately. Any feedback on the changes?

**Comment by danpaul000** [comment]
CI is happy, docs are now live on spl.solana.com

**Pull request merged**
