### PR TITLE
Bump dependencies from 1.3.8 to 1.3.9

### PR DESCRIPTION
**Pull request by jstarry**

### CODE REVIEW

**Comment by joncinque** [comment]
This might fail because web3 needs to get bumped up in token/js and token-swap/js.  In each, client/util/send-and-confirm-transaction.js will need to correctly call `sendAndConfirmTransaction` with the new parameters:
```
  return realSendAndConfirmTransaction(connection, transaction, signers, {
    skipPreflight: true,
    commitment: 'recent',
  });
```

**Comment by jstarry** [comment]
@joncinque I'm not aware of any incompatibilities between 1.3.8 and 1.3.9. I don't expect any issues with using an older web3

**Comment by joncinque** [comment]
@jstarry I might have it wrong, but I wanted to flag it up in case an issue does come up

**Comment by joncinque** [comment]
Looks good!  Maybe what I was seeing had to do with web3 updates then

**Comment by jstarry** [comment]
Ok, thanks!

**Pull request merged**
