### PR TITLE
Multi delegate program draft

### PR DESCRIPTION
**Pull request by Arrowana**
Added some thoughts into a proposal and wrote a draft of the program process_instruction

it is loose but i don't want to over constrain with checks until the design looks sound.

### CODE REVIEW

**Comment by jamesrp13** [comment]
@Arrowana thanks for putting this together. My concern about multi-delegation happening in a separate program from the token program is the attack vector (or just inconvenience) of undercutting existing delegates by reassigning the underlying single delegate on a token account. 

E.g. a user has 5 delegates approved for a USDC account, then they submit a transaction to another program with the intent of adding it as a 6th delegate in the same USDC account. What they don't realize is that this program doesn't use the same multi-delegate program and instead sets the delegate on the token account itself, thereby removing the connection with the multi-delegate program and effectively removing the first 5 delegates.

I personally think the addition of something to the Token Program itself to avoid this possibility is worth not putting the onus onto the end user to know that there are various approaches to token delegation and choosing programs according to which they want.

That being said, I'm curious how this fits into what you've designed, if you have suggestions for mitigating the problem I mentioned above, etc.

**Comment by Arrowana** [comment]
Having it in spl was one way to share a way of doing it for everyone.

There are definitely some issues that could be eliminated if it was directly in the token program:
- Re-approving PDA "reapproves" all the previous delegates
- Approving something else once shortcircuits the multi delegate
- Looks like another token transfer with the delegate signing without extra accounts

But i don't think the trivial relationship between delegate and a token transfer (same for owner or delegate) has to/can go away so it feels like those issues will remain.

The token transfer will need the multi delegate account and the underlying delegate, or were you thinking on storing all the delegates under the token account itself?

**Comment by jamesrp13** [comment]
I don't have any issue storing the multi-delegate in a separate program. The only thing I'm not loving about having a separate program is how easy it is to short-circuit the multi-delegate (E.g. user simply interacting with a program that adds itself as the token program delegate directly rather than using the multi-delegate program). 

I would absolutely love to find a solution for that.

**Comment by jamesrp13** [comment]
Noting that issue #3858 has some discussion going on about this

**Comment by nickgarfield** [comment]
Ah, I didn't realize this PR was already underway. We've outlined a data model in https://github.com/solana-labs/solana-program-library/issues/3858#issuecomment-1334782657 that could fit into token22 with minimal changes to the existing interfaces. Would love to get your feedback on it @Arrowana! 

As mentioned in the comments above, the main concern with pushing the multi-delegate implementation into a secondary program is that the authority can be short-circuited by other programs. Ideally, approvals should be a non-rivalrous. The token22 program seems like an ideal opportunity to solve this problem at the root level and remove the artificial scarcity currently limiting users to one approved delegate per token account. This would massively unblock payments developers, finally allowing them to re-create the experiences users have come to expect from traditional fiat services.

**Pull request closed without merging**
