### PR TITLE
README: Add program and crate information

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

We have a lot of crates and packages in SPL, but no way to see them all from the top-level.

#### Solution

Add info in the README

### CODE REVIEW

**Comment by ngundotra** [comment]
There's also `spl-account-compression` and `@solana/spl-account-compression`!

**Comment by joncinque** [comment]
Ah darn, yes! Thanks for noticing @ngundotra :pray: is [3345beb](https://github.com/solana-labs/solana-program-library/pull/4055/commits/3345beb315abe64edeecfde1a1146c5d4ca61f8a) good?

**Comment by ngundotra** [comment]
Yup looks good! Thanks for including `spl-noop` & `spl-concurrent-merkle-tree` as well.

Yeah, docs are here: https://solana-labs.github.io/solana-program-library/account-compression/sdk/docs/

**Review by 2501babe — DISMISSED** [review]
incidentally i verified all the urls here resolve except the crates.io ones because ig cloudfront doesnt like curl

**Pull request merged**
