### PR TITLE
[account compression] Clean up tests

### PR DESCRIPTION
**Pull request by ngundotra**
It is not eminently clear that zero-length instructions work, so add a test case for this in e2e tests.

Addresses concern in #5092

### CODE REVIEW

**Comment by ngundotra** [comment]
@jnwng @buffalojoec @joncinque Before adding some features to SPL account compression, do you guys have any preference on how the SPL Account Compression test suite is written?

**Comment by buffalojoec** [comment]
> @jnwng @buffalojoec @joncinque Before adding some features to SPL account compression (in follow up PRs), do you guys have any preference on how the SPL Account Compression test suite is written?

From what I can tell all of the JS libraries do tests their own way, but we are migrating all of them to use `pnpm` over `npm` or `yarn`, so if you wanted to configure your `package.json` and test suite for that, it would be a help. Shouldn't be much of a change!

**Comment by buffalojoec** [comment]
@joncinque might not be the place to discuss but this did remind me of Solana Bankrun, which we can use to test our JS libs.
https://kevinheavey.github.io/solana-bankrun/

**Comment by ngundotra** [comment]
Okay, I actually split up the tests into a few different spots, should run a bit faster on local now since they can be parallelized by jest. Also way easier to read now.

Should be evident from the `tests/accounts/canopy.test.ts` that zero length transfer works.

**Comment by joncinque** [comment]
> Do you guys have any preference on how the SPL Account Compression test suite is written?

Jest is normally the recommended test suite over mocha. And definitely use bankrun rather than spinning up a test validator to test against, if you can!

**Pull request closed without merging**
