### PR TITLE
[spl-token] cli: make gc return one json object when using --output json

### PR DESCRIPTION
**Pull request by paul-schaaf**
```
➜  cli git:(master) ✗ spl-token-local gc --close-empty-associated-accounts --output json
{
  "commandName": "gc",
  "commandOutput": {
    "cliSignatures": [
      {
        "signature": "2UR7JeHAFPwMFr2fbDJRbegE6C5gGF2usVPLfzp5iu1U3KKniRgDwnYexFCaDk2rbsTMdmny366eUheHsmccEujU"
      },
      {
        "signature": "5K9VYr4mTnDQ6cB1pAfyTFR33ck8dm3ficV4McU99YV47ixg3F8MMLQFAbPYXC4iuw4tYZecE4YnWSU3wP9gtxwi"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by paul-schaaf** [comment]
closes #2599

**Comment by paul-schaaf** [comment]
@CriesofCarrots maybe it makes sense to move CliSignatures and CliSignOnlyDataMultiple (maybe we can find a better name for this one..) into the solana output cli crate? theyre not token specific

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots maybe it makes sense to move CliSignatures and CliSignOnlyDataMultiple (maybe we can find a better name for this one..) into the solana output cli crate? theyre not token specific

Yep, that makes a lot of sense, especially since the singletons are in that crate. Can you PR?
It will take a while to get released so it can be used in SPL.

> (maybe we can find a better name for this one..)

Hmm, I don't have any great ideas. We typically just add an "s". CliSignOnlyDatas is weird for obvious reasons 😆, but maybe the most consistent? Wdyt?

**Comment by CriesofCarrots** [comment]
@paul-schaaf , just checking in. Are you still interested in wrapping this one up? I have my eyes peeled for a monorepo PR from you to upstream those Cli structs :)

**Comment by paul-schaaf** [comment]
blocked by https://github.com/solana-labs/solana/pull/22531

hey @CriesofCarrots sorry this took so long, I had forgotten about it

**Pull request closed without merging**
