### PR TITLE
Governance: remove Rent from the CreateGovernance doc

### PR DESCRIPTION
**Pull request by 0xShuk**

### CODE REVIEW

**Comment by buffalojoec** [comment]
@0xShuk Is this still relevant? And should it be applied to other instructions?

**Comment by buffalojoec** [comment]
It looks like there's more than one to update. The PR where most of this was changed is #2838.
- [`CreateGovernance`](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_governance.rs#L31-L42)
- [`CreateProgramGovernance`](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_program_governance.rs#L37-L53)
- [`CreateMintGovernance`](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_mint_governance.rs#L39-L54)
- [`CreateTokenGovernance`](https://github.com/solana-labs/solana-program-library/blob/eeb1ca9601afb3675011063cc20d87fbb3b693aa/governance/program/src/processor/process_create_token_governance.rs#L37-L52)

**Comment by SebastianBor** [comment]
> It looks like there's more than one to update. The PR where most of this was changed is #2838.
> 

Correct, the `Rent` account is not used and it applies to all `CreateXxxxGovernance` instructions

**Comment by 0xShuk** [comment]
@buffalojoec @SebastianBor I have created a new PR which includes all four ixs: https://github.com/solana-labs/solana-program-library/pull/5949

**Pull request closed without merging**
