### PR TITLE
[program] Fix InitializeAccount2's comment

### PR DESCRIPTION
**Pull request by mohanson**

### CODE REVIEW

**Review by SMSDAO — COMMENTED** [review]
Nothing was change in code

**Comment by SMSDAO** [comment]
What line number if I'm wrong

**Comment by mohanson** [comment]
image

**Comment by joncinque** [comment]
The token program implementation is unmaintained in this repo, but I haven't made that clear yet. If you want to contribute your change, please open a PR at https://github.com/solana-program/token

**Pull request closed without merging**
