### PR TITLE
token: fix ts for @solana/spl-token

### PR DESCRIPTION
**Pull request by fanatid**
Fix typescript definitions for https://github.com/solana-labs/solana-program-library/pull/1802

### CODE REVIEW

**Comment by joncinque** [comment]
Hi there, thanks for noticing this and providing a contribution!  Unfortunately, since this is just a declaration, TS doesn't allow setting a default, so it'll have to be:
```
allowOwnerOffCurve: boolean,
```
Could you make that fix, and also apply it to the `module.flow.js` while you're at it?

**Comment by yihau** [comment]
Hey! Thank you!!!

BTW, this PR also can solve 
https://github.com/solana-labs/solana-program-library/issues/1997
https://github.com/solana-labs/solana-program-library/pull/2145

**Comment by fanatid** [comment]
@joncinque thanks for the fix of fix :smile: 
Updated!

**Comment by TimonPeng** [comment]
I think it should be `allowOwnerOffCurve?: boolean`, not required.

**Comment by fanatid** [comment]
@TimonPeng thanks!

**Comment by joncinque** [comment]
Great point, thanks @TimonPeng ! Once this passes CI I'll merge it in

**Pull request merged**
