### PR TITLE
Increase compute max units due to changes in handling of memory ops

### PR DESCRIPTION
**Pull request by dmakarov**
bpf-tools v1.21 changed implementation of memory operations, which results in larger instruction numbers for the same operations. This PR adjusts the compute limits in tests affected by the changes in bpf-tools.

### CODE REVIEW

**Comment by joncinque** [comment]
Would you mind also updating the "last known" numbers in the comments? this will help figure out how CU usage evolves over time

**Comment by dmakarov** [comment]
I would gladly update the comments, but not sure how to get this information. Are this counts printed on RUSTLOG set to debug?

**Comment by joncinque** [comment]
Oh right, that part is not very clear, and a bit annoying.  You essentially have to read through the output of `cargo test-bpf` and match up the test to the instruction count printed by default on the console.

In that case, don't worry about it, I'm doing some work around there soon, so I'll update them at that point :smile:

**Review by joncinque — APPROVED** [review]

**Comment by dmakarov** [comment]
Actually after the update the tests still fail. For example, for initialize_mint I get this message

```
[2021-12-21T01:44:47.393203000Z DEBUG solana_runtime::message_processor] Program Token22gQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2500 of 2500 compute units
[2021-12-21T01:44:47.393231000Z DEBUG solana_runtime::message_processor] Program failed to complete: exceeded maximum number of instructions allowed (2500) at instruction #13625
```
Where does this 2500 limit come from if I updated it to 5000?

**Comment by joncinque** [comment]
This is my fault for not pointing it out -- you'll also have to update these numbers in `token/program-2022`: https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/tests/assert_instruction_count.rs

**Pull request merged**
