### PR TITLE
token-js: Add sync version of getAssociatedTokenAddress

### LINKED ISSUE #3050: token-js: Add sync version of getAssociatedTokenAddress
https://github.com/solana-labs/solana-program-library/blob/48fbb5b7c49ea35848442bba470b89331dea2b2b/token/js/src/state/mint.ts#L114

This references (async) PublicKey.findProgramAddress, which references (async) PublicKey.createProgramAddress...but I'm not sure why https://github.com/solana-labs/solana-web3.js/blob/d93efdf/src/publickey.ts#L146 needs to be async. I may be missing something! It would just be nice to be able to neatly call this synchronously in a test or whatnot without bubbling up async/await.

### PR DESCRIPTION
**Pull request by dboures**
closes #3050

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
Looks good! Any chance you can add a test to make sure that both functions produce the same result?

**Comment by dboures** [comment]
Thanks for the quick review!. The test has been added.

**Comment by dboures** [comment]
Thanks for the quick review!. The test has been added.

**Review by joncinque — APPROVED** [review]
Thanks for that! We just had an issue in the lockfile, which should be resolved.  I'll merge this once it passes CI

**Comment by dboures** [comment]
Ah thanks! I should have taken a closer look at the CI. Now I know for next time

**Comment by joncinque** [comment]
No worries, it's not clear that it's actually edited by hand :grimacing:

**Comment by joncinque** [comment]
Thanks for your contribution!

**Comment by charlie-amihan** [comment]
Thanks <3

**Pull request merged**
