### PR TITLE
ci broke

### PR DESCRIPTION
**Pull request by 2501babe**
the token job runs out of disk space. pain

### CODE REVIEW

**Comment by 2501babe** [comment]
annoyingly, cargo-test-sbf didnt even fail like it was supposed to... anyway

```HANA before deps
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   65G   19G  79% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        [14](https://github.com/solana-labs/solana-program-library/actions/runs/6141650423/job/16662237900?pr=5231#step:8:15)G  4.1G  9.0G  31% /mnt
tmpfs           694M   12K  694M   1% /run/user/1001
```

```HANA after deps
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   66G   18G  80% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   12K  694M   1% /run/user/1001
```

```HANA before test
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   66G   18G  80% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   [12](https://github.com/solana-labs/solana-program-library/actions/runs/6141650423/job/16662237900?pr=5231#step:9:13)K  694M   1% /run/user/1001
```

```HANA after test
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   84G   57M 100% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  1.1M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        14G  4.1G  9.0G  31% /mnt
tmpfs           694M   12K  694M   1% /run/user/1001
```

**Comment by 2501babe** [comment]
ok that didnt help at all it still uses up nearly the whole disk

**Comment by buffalojoec** [comment]
Any idea why this would randomly just start happening?

I wiped a cache in the CI a bit ago, did I nuke our CI? Lol

**Comment by 2501babe** [comment]
my best guess is just dependency size creep, ie we were fluctuating close to but fully below the disk size limit up until recently but are now fluctuating below or above the limit. you can see that just building tests takes 20gb. whenever cargo has to make a space/time tradeoff, it chooses time, and we are now getting fucked by that

i still have no idea why its using 66gb to start tho, this seems like the most obvious thing to attack

**Comment by 2501babe** [comment]
ok it uses 63gb before we even do literally anything so i think this ubuntu image just sucks

**Comment by buffalojoec** [comment]
> btw what do you mean you deleted the caches? do they persist between runs? i assumed they were to cache things between jobs in the same run

It creates a cache for things like `cargo-build-sbf` and only rebuilds the cache when certain things change. I blew the `cargo-build-sbf` one away trying to make CI pull in a fresh Solana download from `curl` or whatever thinking it still had a cached `master` branch in it. I wonder if it was just a matter of time before that particular cache needed to be rebuilt and we hit size limits.

**Comment by 2501babe** [comment]
i dont think the cache is the problem. at least, disk usage does not change when it pulls in `~/.cargo`. i have no idea _where_ it is because i _also_ dont see any new block devices show up. the most fruitful-seeming path to me rn is deleting shit off the base image to kick this can down the road

**Comment by 2501babe** [comment]
absolutely astounding
```
google-chrome-stable               320,121      installed
temurin-17-jdk                     322,669      installed
dotnet-sdk-6.0                     337,379      installed
dotnet-sdk-7.0                     404,208      installed
microsoft-edge-stable              526,382      installed
azure-cli                          592,242      installed
google-cloud-sdk                   737,423      installed
```

**Comment by 2501babe** [comment]
ok by removing obvious garbage ive managed to free 10gb on the image, i think this is a good solution for now to get our shit moving again. ill consult with jon later to see if he has more erudite and delicate suggestions to fix this

**Comment by buffalojoec** [comment]
> ok by removing obvious garbage ive managed to free 10gb on the image, i think this is a good solution for now to get our shit moving again. ill consult with jon later to see if he has more erudite and delicate suggestions to fix this

sgtm lmk when ready

**Review by buffalojoec — APPROVED** [review]
wow that's a lot of unnecessary packages!

**Pull request merged**
