### PR TITLE
Extensions doc metadata js example

### PR DESCRIPTION
**Pull request by MohammedAlabd**
adding js examples for the metadata part of the token22 extension

### CODE REVIEW

**Comment by MohammedAlabd** [comment]
not sure if you have other plans for it but I was working on a course on that extension and I figured that I could drop these here quickly.

So sorry if I am stepping on somebody else's work

**Review by joncinque — COMMENTED** [review]
This is excellent work, thanks so much! I confirm that it all works in my local testing.

We try to keep these examples in line with the `examples` at https://github.com/solana-labs/solana-program-library/tree/master/token/js/examples -- would you mind combining all of these into a file called `metadata.ts` containing all of these cases?

**Comment by MohammedAlabd** [comment]
@joncinque Yes sure I will do that tomorrow

**Comment by MohammedAlabd** [comment]
@joncinque can you take another look please?

**Review by joncinque — APPROVED** [review]
Perfect, thanks again!

**Pull request merged**
