### PR TITLE
Fix update-solana-dependencies.sh to work on osx

### PR DESCRIPTION
**Pull request by alessandrod**
Bump deps to 1.10.0 and tweak `update-solana-dependencies.sh` to work on osx.

### CODE REVIEW

**Comment by alessandrod** [comment]
For context: this is currently needed to run `scripts/build-downstream-projects.sh` in the monorepo or it will pull the solana crates from crates.io

**Comment by CriesofCarrots** [comment]
Hmm, `scripts/build-downstream-projects.sh` works for me on my mac. I did have to install gnused, though.
I also usually use a patch like this to run against my spl clone:
```
diff --git a/scripts/build-downstream-projects.sh b/scripts/build-downstream-projects.sh
index a2181ebe4..7c499a58f 100755
--- a/scripts/build-downstream-projects.sh
+++ b/scripts/build-downstream-projects.sh
@@ -60,9 +60,9 @@ example_helloworld() {
 spl() {
   (
     set -x
-    rm -rf spl
-    git clone https://github.com/solana-labs/solana-program-library.git spl
-    cd spl
+    # rm -rf spl
+    # git clone https://github.com/solana-labs/solana-program-library.git spl
+    cd /Users/xxx/solana-program-library

     ./patch.crates-io.sh "$solana_dir"
 ```

**Comment by alessandrod** [comment]
Oh I missed that `build-downstream-projects.sh` bumps the version through `./patch.crates-io.sh`. Then just the extended regex fix should be sufficient. 

And yes installing gnused would probably work, but turning into ERE makes it work with BSD sed as well, and removes a footgun both @dmakarov and I wasted some time today 😅

**Comment by CriesofCarrots** [comment]
As long as it doesn't break the monorepo CI, I'm all for it :)

**Comment by alessandrod** [comment]
I've tried the regex with GNU sed on ubuntu 20.04 so I'm reasonably sure it should work (famous last words)

**Comment by dmakarov** [comment]
The SPL project's Cargo.toml is patched by 

However, that doesn't help on my system at least. For example, I see these messages when cargo test is started by cargo-test-bpf (same happens when `cargo build` runst)

```
/Users/dmakarov/.rustup/toolchains/1.57.0-x86_64-apple-darwin/bin/cargo test --manifest-path /Users/dmakarov/work/git/solana/target/downstream-projects/spl/stateless-asks/program/Cargo.toml --features test-bpf -- --test-threads=1
warning: Patch `solana-account-decoder v1.10.0 (/Users/dmakarov/work/git/solana/account-decoder)` was not used in the crate graph.
Patch `solana-banks-client v1.10.0 (/Users/dmakarov/work/git/solana/banks-client)` was not used in the crate graph.
Patch `solana-banks-server v1.10.0 (/Users/dmakarov/work/git/solana/banks-server)` was not used in the crate graph.
Patch `solana-bpf-loader-program v1.10.0 (/Users/dmakarov/work/git/solana/programs/bpf_loader)` was not used in the crate graph.
Patch `solana-clap-utils v1.10.0 (/Users/dmakarov/work/git/solana/clap-utils)` was not used in the crate graph.
Patch `solana-cli-config v1.10.0 (/Users/dmakarov/work/git/solana/cli-config)` was not used in the crate graph.
Patch `solana-cli-output v1.10.0 (/Users/dmakarov/work/git/solana/cli-output)` was not used in the crate graph.
Patch `solana-client v1.10.0 (/Users/dmakarov/work/git/solana/client)` was not used in the crate graph.
Patch `solana-core v1.10.0 (/Users/dmakarov/work/git/solana/core)` was not used in the crate graph.
Patch `solana-logger v1.10.0 (/Users/dmakarov/work/git/solana/logger)` was not used in the crate graph.
Patch `solana-notifier v1.10.0 (/Users/dmakarov/work/git/solana/notifier)` was not used in the crate graph.
Patch `solana-program v1.10.0 (/Users/dmakarov/work/git/solana/sdk/program)` was not used in the crate graph.
Patch `solana-program-test v1.10.0 (/Users/dmakarov/work/git/solana/program-test)` was not used in the crate graph.
Patch `solana-remote-wallet v1.10.0 (/Users/dmakarov/work/git/solana/remote-wallet)` was not used in the crate graph.
Patch `solana-runtime v1.10.0 (/Users/dmakarov/work/git/solana/runtime)` was not used in the crate graph.
Patch `solana-sdk v1.10.0 (/Users/dmakarov/work/git/solana/sdk)` was not used in the crate graph.
Patch `solana-stake-program v1.10.0 (/Users/dmakarov/work/git/solana/programs/stake)` was not used in the crate graph.
Patch `solana-transaction-status v1.10.0 (/Users/dmakarov/work/git/solana/transaction-status)` was not used in the crate graph.
Patch `solana-version v1.10.0 (/Users/dmakarov/work/git/solana/version)` was not used in the crate graph.
Patch `solana-vote-program v1.10.0 (/Users/dmakarov/work/git/solana/programs/vote)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

So on my system, SPL is not built using the local clone of solana repository. Instead the version downloaded from crates.io is used always.

**Comment by alessandrod** [comment]
@dmakarov are you sure build-downstream-projects.sh is building a fork of spl that includes this patch? It'll remove the existing tree and do a fresh clone of main, so you need to tweak the script to test the patch. This is what I did:

```
diff --git a/scripts/build-downstream-projects.sh b/scripts/build-downstream-projects.sh
index a2181ebe4..f4b8461af 100755
--- a/scripts/build-downstream-projects.sh
+++ b/scripts/build-downstream-projects.sh
@@ -61,7 +61,8 @@ spl() {
   (
     set -x
     rm -rf spl
-    git clone https://github.com/solana-labs/solana-program-library.git spl
+    # git clone https://github.com/solana-labs/solana-program-library.git spl
+    cp -a $HOME/src/solana/solana-program-library spl
     cd spl
 
     ./patch.crates-io.sh "$solana_dir"
@@ -101,6 +102,6 @@ EOF
 }
```

Where `$HOME/src/solana-program-library` includes this patch.

**Comment by dmakarov** [comment]
never mind. the patch works perfectly.

**Pull request merged**
