### PR TITLE
token-lending: Migrate to `@solana/buffer-layout`

### LINKED ISSUE #2534: Migrate to @solana/buffer-layout
The `buffer-layout` package used here as a dependency lacks proper typing, which causes issues with downstream libraries depending on the token program TypeScript code.

Solana Labs maintains a buffer-layout implementation with types already:
https://github.com/solana-labs/buffer-layout

I suggest to change the dependency to that implementation.

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
Fixes #2534.

### CODE REVIEW

**Comment by jordansexton** [comment]
Looks like there's a lot of overlap with #2634. I think it may be better to get https://github.com/solana-labs/buffer-layout/pull/1 merged first and then use https://github.com/solana-labs/buffer-layout-utils/ so we don't have to cast things and we can DRY this up.

**Comment by jordansexton** [comment]
Both `@solana/buffer-layout` and `@solana/buffer-layout-utils` have been released.

@abhimanyusinghgaur & @israelidanny, it may be worth figuring out how to combine your efforts on this one.

**Comment by israelidanny** [comment]
@jordansexton from a quick read of this PR, it mostly does the same thing I did in https://github.com/solana-labs/solana-program-library/pull/2634 minus generics. If https://github.com/solana-labs/solana-program-library/pull/2634 is pushed, I think it will cover everything this PR is designed to contribute.

**Comment by abhimanyusinghgaur** [comment]
Thanks @israelidanny. Closing this PR.

**Pull request closed without merging**
