### PR TITLE
fix: Use COptionPubkeyLayout for all COption fields

### PR DESCRIPTION
**Pull request by qiweiii**
resolve: #6170

### CODE REVIEW

**Review by buffalojoec — COMMENTED** [review]
Looks great! Do you mind just adding some test coverage to the instructions so we can assert this works properly with `null` authorities?

You can just add a few more lines to some of the existing ones like `e2e-2022/closeMint.test.ts`, etc.

**Comment by qiweiii** [comment]
@buffalojoec  I am not exactly sure how this should be tested, I added a test case, is that what we expect

**Comment by buffalojoec** [comment]
> @buffalojoec I am not exactly sure how this should be tested, I added a test case, is that what we expect

It actually appears the `MintCloseAuthority` and `setAuthority` have some coverage for working with null authority values. I went ahead and added the coverage for `InitializeMint` and `InitializeMint2`!

**Review by buffalojoec — APPROVED** [review]
Thanks very much for this!

celebrate

**Pull request merged**
