### PR TITLE
Update Solana to 1.16.1 and Rust to 1.69

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

The 1.16 Solana crates are out, but SPL is still on 1.14 and needs the new functionality.

#### Solution

Update the:

* rust version to 1.69
* nightly to 2023-04-19
* solana tools to 1.16.1
* solana crates to 1.16.1
* borsh to 0.10

And fix:

* new clippy warnings
* deprecated warnings in the new solana crates

This may take some time to usher through CI, so marking as a draft

### CODE REVIEW

**Comment by joncinque** [comment]
All right, this is finally good to go!

**Review by samkim-crypto — DISMISSED** [review]
Thanks for all the changes. Looks good to me!

**Comment by govindtripathi** [comment]
Good Day,

I would like to know more about such receiving email.

Thanks & Regards

**Comment by joncinque** [comment]
Rebased this on top of https://github.com/solana-labs/solana-program-library/pull/4595, so once it passes CI, will merge!

**Pull request merged**
