### PR TITLE
Switch to Github Actions for CI

### PR DESCRIPTION
**Pull request by jstarry**
Fixes: https://github.com/solana-labs/solana-program-library/issues/584

### CODE REVIEW

**Comment by jstarry** [comment]
Down from 1hr+ to 7.5min

**Comment by mvines** [comment]
.github/workflows/pull-request.yml is pretty gross, I'm failing in some random yaml world and have no ability to reproduce locally.  Debugging via CI is the worst 💩 
I guess it's worth the speed up overall 😭

**Comment by jstarry** [comment]
@mvines oops I went overboard with the config, I can either reintroduce the PR for full review or simplify in a follow up

**Comment by mvines** [comment]
Simplifying in a follow-up wfm.   Minimal CI-specific crap, keep things as much as possible in shell scripts that can be also run and debug locally is the only way to keep CI from ruling you.

**Pull request merged**
