### PR TITLE
spl-token-cli: Add bench subcommand

### PR DESCRIPTION
**Pull request by mvines**
Add a `spl-token bench` subcommand with some basic token benchmarking facilities.

```
SUBCOMMANDS:
    close-accounts     Close multiple token accounts used for benchmarking
    create-accounts    Create multiple token accounts for benchmarking
    deposit-into       Deposit tokens into multiple accounts
    withdraw-from      Withdraw tokens from multiple accounts
```

### CODE REVIEW

**Comment by jstarry** [comment]
fyi there are some downstream clippy issues here: https://buildkite.com/solana-labs/solana/builds/54415#fa12ecff-eebb-41cc-9246-2639ae1762f9

I guess we'll need to setup a similar clippy check in this repo soon

**Comment by mvines** [comment]
Clippy is present already.  The problems are:
1. Solana 1.8's RpcClient deprecates the fee calculator and friends in v1.7 too aggressively.   SPL is still on v1.7 but it has no way to migrated off the deprecated functionally before upgrading to v1.8.
2. The `progress_bar.set_message()` signature in 1.8 changes from 1.7, so similar to (1)

Will suppress warnings as needed via https://github.com/solana-labs/solana-program-library/pull/2376

**Comment by jstarry** [comment]
Ah thanks, I was just digging into this and was getting confused what was happening here

**Comment by mvines** [comment]
I've almost got it fixed here

**Comment by mvines** [comment]
https://github.com/solana-labs/solana-program-library/pull/2376/commits/ff5591745fb37fd486427f9225e2d5e7bbb78231 should hopefully fix the downstream build once it lands

**Pull request merged**
