### PR TITLE
Added an instruction to lendinginstruction enum, added to the packing…

### PR DESCRIPTION
**Pull request by allanperlee**
… and unpacking of lendinginstruction enum, added a match pattern to processor CloseObligationAccount instruction, will continue to make modifications such as add a function for closing obligation account in processor.rs; PR is not final.

### CODE REVIEW

**Comment by jordansexton** [comment]
Thanks for this @allanperlee! Just let me know when it's ready to take a look at

**Comment by allanperlee** [comment]
@jordansexton Ill let you know man, thanks for the response

**Comment by allanperlee** [comment]
@jordansexton where can I find documentation for using spl_token methods such as `spl_token_mint`? I found a method `close_account` but it's unclear why spl_token prefixed methods are used.

**Comment by allanperlee** [comment]
@jordansexton Do the programs need to be built with `cargo build bpf` for pull requests?

**Comment by jordansexton** [comment]
It's a good idea to run `cargo build-bpf` and also `cargo test-bpf` so you know everything compiles and passes

**Comment by allanperlee** [comment]
A small unit test was made with the `close_obligation_account` instruction in one of the test files. The tests passed, but the build failed with `cargo test-bpf`. One of the errors was `error: linking with `cc` failed: exit status: 1`. Is this an issue?

**Comment by allanperlee** [comment]
@jordansexton  It's ready for review.

**Comment by jordansexton** [comment]
It looks like there may still be merge conflicts?

**Comment by allanperlee** [comment]
@jordansexton Yes, there are. I need help with this.

**Comment by jordansexton** [comment]
Sure. This PR is opened from the master branch of your fork, so can you add me as a contributor to there so I can work on it?

**Pull request closed without merging**
