### PR TITLE
Token cli: spl-token accounts improvements

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Display changes mentioned in #1429 

- Updates display output, and adds `--verbose` handling. Examples in comments

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
```
$ spl-token accounts

Token                                        Balance
----------------------------------------------------------
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 10.55
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 10.1 (Aux-1)
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 0 (Aux-2)
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW 148.5
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW 0 (Aux-1)
```

```
$ spl-token accounts -v

Token                                        Account                                      Balance
------------------------------------------------------------------------------------------------------
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 65fqVfZSXzhxMYgr1m9yN46rQ3gEUNBZbBRyQEraAMyt 10.55
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 4fYNw3dojWmQ4dXtSGE9epjRGy9pFSx62YypT7avPYvA 10.1 (Aux-1)
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 7aHDubg5FBYj1SgmyBgU3ZJdtfuqYCQsJQK2pTR5JUqr 0 (Aux-2)
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW Az6rZAw2yMhB2SE67N4sUXQDiufupnzXTz3CmgRQHNKJ 148.5
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW CYRJWqiSjLitBAcRxPvWpgX3s5TvmN2SuRY3eEYypFvT 0 (Aux-1)

* Please run `spl-token gc` to clean up Aux accounts
```

**Comment by CriesofCarrots** [comment]
After running `spl-token gc`:
```
$ spl-token accounts

Token                                        Balance
----------------------------------------------------------
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 20.65
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW 148.5
```

```
$ spl-token accounts -v

Token                                        Account                                      Balance
------------------------------------------------------------------------------------------------------
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 65fqVfZSXzhxMYgr1m9yN46rQ3gEUNBZbBRyQEraAMyt 20.65
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW Az6rZAw2yMhB2SE67N4sUXQDiufupnzXTz3CmgRQHNKJ 148.5
```

**Comment by CriesofCarrots** [comment]
Specify mint:
```
$ spl-token accounts 2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y

Balance
-------------
10.55
10.1 (Aux-1)
0 (Aux-2)

* Please run `spl-token gc` to clean up Aux accounts
```

This one gets a little terse without verbose, and after running `spl-token gc`:
```
$ spl-token accounts 2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y

Balance
-------------
20.65
```

```
$ spl-token accounts 2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y -v

Account                                      Balance
---------------------------------------------------------
65fqVfZSXzhxMYgr1m9yN46rQ3gEUNBZbBRyQEraAMyt 20.65
```

**Comment by CriesofCarrots** [comment]
With frozen accounts:
```
$ spl-token accounts

Token                                        Balance
----------------------------------------------------------
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 10.55 ⚠️  Frozen
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 10.1 (Aux-1) ⚠️  Frozen
2cCuJBkhgAy4qoARtegzhYbNPHh1YpGw2J5rd4m2uw5y 0 (Aux-2)
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW 148.5
CBY7sfWepcLXpphrC4gyKqN5M1ma2L7Lx2JtucsFUvtW 0 (Aux-1)

* Please run `spl-token gc` to clean up Aux accounts
```

**Review by t-nelson — DISMISSED** [review]
LGTM!  Just a couple nits

**Comment by t-nelson** [comment]
> I'm not in love this how this looks, but I think frozen will not be super common

This could be improved if we were to pre-process the stringified amounts for the max length and use that as the width in the format specifier.  Similarly, we could fix the aux tag width, assuming one digit of aux count (any more and they deserve some jank!)

**Comment by CriesofCarrots** [comment]
> > I'm not in love this how this looks, but I think frozen will not be super common
> 
> This could be improved if we were to pre-process the stringified amounts for the max formatted length and use that as the width in the format specifier. Similarly, we could fix the aux tag width, assuming one digit of aux count (any more and they deserve some jank!)

Thanks @t-nelson! The fixed-width balance column looks tons better. Examples updated above. With that change, I'm happy with the frozen markers as well.

**Comment by t-nelson** [comment]
> Thanks @t-nelson! The fixed-width balance column looks tons better. Examples updated above. With that change, I'm happy with the frozen markers as well.

:heart_eyes:
Much better!  This is totally good to go as is, so feel free to merge as is, but... :wink: 

WDYT about two spaces between columns and fixed width aux labels

**Comment by CriesofCarrots** [comment]
> WDYT about two spaces between columns and fixed width aux labels

😁 done! https://github.com/solana-labs/solana-program-library/pull/1440/commits/73eeed9f0b3fe5fecc3ddee42247e5c0ffcd2b17

**Review by t-nelson — APPROVED** [review]
:pray: :shipit:

**Pull request merged**
