### PR TITLE
token 2022: make `IncorrectMintAuthority` a `TokenError`

### PR DESCRIPTION
**Pull request by buffalojoec**
This PR makes `IncorrectMintAuthority` a `TokenError`, rather than a `TokenMetadataError`, since it will likely be used across multiple extension processors (such as SPL Token Group).

### CODE REVIEW

**Comment by buffalojoec** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5512** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5512" target="_blank">Graphite</a> 
    * **PR #5548** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5548" target="_blank">Graphite</a> 
      * **PR #5549** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5549" target="_blank">Graphite</a> 
        * **PR #5595** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5595" target="_blank">Graphite</a> 
          * **PR #5596** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5596" target="_blank">Graphite</a>  👈
        * **PR #5593** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5593" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5596?utm_source=stack-comment).

**Comment by buffalojoec** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5512** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5512" target="_blank">Graphite</a> 
    * **PR #5548** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5548" target="_blank">Graphite</a> 
      * **PR #5549** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5549" target="_blank">Graphite</a> 
        * **PR #5595** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5595" target="_blank">Graphite</a> 
          * **PR #5596** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5596" target="_blank">Graphite</a>  👈
        * **PR #5593** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5593" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/5596?utm_source=stack-comment).

**Review by joncinque — COMMENTED** [review]
Can we instead switch to the current `TokenError::OwnerMismatch` instead of adding a new error?

**Comment by joncinque** [comment]
> Wouldn't that be confusing to some people since the mint authority is a separate thing from the owner?

It's true that `Owner` is a very overloaded term in token, and especially in token-2022. Anytime we validate an owner or authority (freeze, transfer fee, confidential transfer, metadata, metadata pointer, transfer hook, etc etc etc), we call `validate_owner`, which can return `OwnerMismatch`.

If we want to maintain ABI compatibility in Token-2022, it must return the same errors as tokenkeg for things like mint, freeze, and owner. We can make a new error for the other authorities though, and potentially use that new error in instructions that aren't present in tokenkeg. That seems like it'll be needlessly brittle and prone to error though.

We can also decide to break ABI compatibility, but it seems like a lot of work just to fix error text. We could also change the name `OwnerMismatch` to something else, but that might cause other kinds of confusion.

So to me, since we don't have a great alternative, I prefer to stick with what we have in `OwnerMismatch`, even though it's imperfect. What do you think?

**Comment by buffalojoec** [comment]
Going to submit a new PR for the above and close this one.

**Pull request closed without merging**
