### PR TITLE
Don't repack if not needed

### PR DESCRIPTION
**Pull request by jackcmay**
There are cases where the token program only needed to unpack to read data but is instead also repacking that unchanged data

- Don't repack if we don't need to
- Ensure that pack function check initialization
- Cleanup the pack trait by encapsulating stray functions
- Fix some token-swap rot

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Ugh, cbindgen. Fyi @mvines I was seeing this locally running `cbindgen.sh` as well. Seems to only be from the token_swap build, afaict. When I commented out https://github.com/solana-labs/solana-program-library/blob/6761f440ab98159f53bbda9658edc685bc11aceb/utils/cgen/src/main.rs#L66 I got the token.h I wanted.

**Comment by mvines** [comment]
There's some really weird bugs in cbindgen :(

**Comment by CriesofCarrots** [comment]
Retry ftw

**Comment by jackcmay** [comment]
Restarted the job and its past cbindgen now

**Pull request merged**
