### PR TITLE
`spl-token` cli - use default config file

### PR DESCRIPTION
**Pull request by jkbpvsc**
## Problem
The `spl-token` uses the argument `-C` to specify the cli config file, if the argument isn't provided a default config file is created, using  the default signer `~/.config/solana/id.json`.
This behavior is inconsistent with the main `solana` cli, where in case the cli config file isn't explicitly passed, the cli will use the default cli config file at `~/.config/solana/cli/config.yml`

## Changes
These changes consolidate the default cli config file loading behavior between the `spl-token` and  `solana`.
If the file is not explicitly specified with `-C`, the default cli config at `~/.config/solana/cli/config.yml` if it exists.

Main [solana cli for reference](https://github.com/solana-labs/solana/blob/master/cli/src/clap_app.rs#L17)

### CODE REVIEW

**Comment by 2501babe** [comment]
this already takes place here: https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/config.rs#L56-L65

**Comment by jkbpvsc** [comment]
Ah I see.
However the same fallback is missing in the `new_with_clients_and_ws_url` where the `cli_config` gets loaded for the `Config` struct.

https://github.com/solana-labs/solana-program-library/blob/master/token/cli/src/config.rs#L115

`Config::new()` calls `Config::new_with_clients_and_ws_url()` which is when the `Config` gets really initialized, the `cli_config` gets loaded and stored.

**Comment by 2501babe** [comment]
ooh yes youre right

**Comment by 2501babe** [comment]
(ci failure is unrelated to this, im in the process of attempting to deal with it)

**Comment by 2501babe** [comment]
oki if you would be so kind as to rebase on master to make ci happy this should be good to go

**Comment by jkbpvsc** [comment]
Merged

**Comment by 2501babe** [comment]
ty for your contribution!

**Pull request merged**
