### PR TITLE
Add Transfer2/Approve2/MintTo2/Burn2 instructions for improved hardware wallet support

### PR DESCRIPTION
**Pull request by mvines**
TODO:
* [x] Write instruction pack/unpack code
* [x] Rebase on #342 
* [x] Tests...

Depends-on: https://github.com/solana-labs/solana-program-library/pull/342
<s>Depends-on: https://github.com/solana-labs/solana-program-library/issues/315</s>
Fixes: https://github.com/solana-labs/solana-program-library/issues/289

### CODE REVIEW

**Comment by mvines** [comment]
@CriesofCarrots - this is ready for review I think.  `./coverage.sh` says I hit all my new code paths. 

@t-nelson - this baby is for you.  Can you review to ensure it'll work for you in Ledgerland.  I don't see why not but more eyes here is better anyway

**Comment by mvines** [comment]
> Code lgtm! Do we want to add docs in the Instruction enum explaining how each Instruction2 differs from the original?

Done

**Review by t-nelson — DISMISSED** [review]
This looks like it'll give me what I need to offer a better token amount UX on the Ledger App.

Are we still envisioning the token symbol strings being kept in an on-device LUT?

**Comment by mvines** [comment]
> Are we still envisioning the token symbol strings being kept in an on-device LUT?

Yeah.   We'll just need a hard coded list

**Pull request merged**
