### PR TITLE
token-swap: Changed Wrap SwapCurve's calculator field into Arc instead of Box

### PR DESCRIPTION
**Pull request by Anurag5086**
Solves issue #2718

### CODE REVIEW

**Comment by joncinque** [comment]
Thanks for the contribution!  It looks like there are some CI issues due to the change.

Be sure to run the following on the program at `token-swap/program`:

* `cargo fmt`: formats the code specially for Rust (you can optionally specify the `--all` flag to do the whole repo)
* `cargo +nightly-2021-12-03 clippy -Zunstable-options --all-targets`: linting. currently CI uses nightly-2021-12-03, but that may change in the future
* `cargo test-bpf`: runs all the tests for the program.  token-swap actually works fine with just `cargo test` since it isn't doing any full environment tests, but all of the other programs need it.

For this, you'll probably just need to replace some `Box::new` calls with `Arc::new`

**Comment by joncinque** [comment]
Ah, it looks like the `token-swap/program/fuzz` needs to be updated too.  Once that's done, this should be good to go

**Comment by joncinque** [comment]
Nice job, thanks for the contribution!

**Comment by Anurag5086** [comment]
Thanks for the merge! :)

**Comment by gitmalong** [comment]
```rust
`(dyn spl_token_swap::curve::calculator::CurveCalculator + 'static)` cannot be shared between threads safely
```

Isn't that `Arc` useless when the struct cannot be shared between threads because it is not `sync`?

**Comment by joncinque** [comment]
PRs are still welcome!

**Pull request merged**
