### PR TITLE
Resolve token lending JS tests for PR 2634

### PR DESCRIPTION
**Pull request by bcrant**
Hey,

I've been tracking PR 2634 fully switch to @solana/buffer-layout (https://github.com/solana-labs/solana-program-library/pull/2634) for a couple of weeks. 

I am working on Convergence hackathon and wanted to move things along so I can continue development for Typescript project. I went ahead and merged latest master into @israelidanny 's changes.

Shouts out @israelidanny for doing the actual hard work here.

Cheers,
Brian

### CODE REVIEW

**Comment by jordansexton** [comment]
Running the tests but looks good to go. I'll plan to merge tomorrow.

**Comment by jordansexton** [comment]
Looks like the lending JS tests failed, can you see what's up?

**Comment by israelidanny** [comment]
@jordansexton I updated `buffer-layout-utils` in the original PR https://github.com/solana-labs/solana-program-library/pull/2634

**Comment by bcrant** [comment]
Updates resumed in https://github.com/solana-labs/solana-program-library/pull/2634 

Closing

**Pull request closed without merging**
